/* Deutschraum: auth responsibilities. Classic scripts preserve HTML handler compatibility. */
function login(m){open('<div class="dialog"><div class="dialog-top"><h2>'+ (m==='login'?'Anmelden':'Registrieren') +'</h2><button class="icon" onclick="close()">✕</button></div><form class="form" style="margin-top:15px" onsubmit="event.preventDefault();finish()"><label>E-Mail<input id="email" required type="email"></label><label>Passwort<input required type="password" minlength="4"></label><button class="primary">'+(m==='login'?'Anmelden':'Konto erstellen')+'</button></form></div>')}
function finish(){let e=email.value.trim().toLowerCase();user={email:e};if(!db.users[e])db.users[e]={done:[],right:0,answers:0,words:[],last:{page:'levels',level:'A1'}};s=db.users[e].last;save();close();view()}
function logout(){user=null;save();view()}
function profile(){let p=prof();open('<div class="dialog"><div class="dialog-top"><h2>Mein Profil</h2><button class="icon" onclick="close()">✕</button></div><p>'+user.email+'</p><p class="muted">'+p.done.length+' Lektionen · '+p.words.length+' Wörter · '+p.answers+' Aufgaben</p></div>')}

/* Existing final account UI and local reset-request compatibility. */
(function(runtime){runtime.auth.installAccountCompatibility=function({languageOptions,db,save}){
  window.login=function(mode){const languages=languageOptions.map(lang=>'<option>'+lang+'</option>').join('');window.open('<div class="dialog"><div class="dialog-top"><h2>'+(mode==='login'?'Anmelden':'Registrieren')+'</h2><button class="icon">✕</button></div><form class="form" style="margin-top:15px" onsubmit="event.preventDefault();finishAccount(\''+mode+'\')"><label>E-Mail<input id="email" required type="email"></label><label>Passwort<input required type="password" minlength="4"></label>'+(mode==='login'?'<button type="button" class="forgot-link" onclick="openPasswordReset()">Passwort vergessen?</button>':'<label>Muttersprache<select id="nativeLanguage" required><option value="">Bitte auswählen</option>'+languages+'</select></label>')+'<button class="primary">'+(mode==='login'?'Anmelden':'Konto erstellen')+'</button></form></div>')};
  window.openPasswordReset=function(){window.open('<div class="dialog compact-dialog"><div class="dialog-top"><h2>Passwort zurücksetzen</h2><button class="icon">✕</button></div><form class="form" onsubmit="event.preventDefault();requestPasswordReset()"><p class="muted">Gib deine registrierte E-Mail-Adresse ein.</p><label>E-Mail<input id="resetEmail" type="email" required></label><button class="primary">Reset-Link anfordern</button><p id="resetStatus" class="task-feedback"></p></form></div>')};
  window.requestPasswordReset=function(){const email=document.getElementById('resetEmail').value.trim();db.passwordResetRequests=Array.isArray(db.passwordResetRequests)?db.passwordResetRequests:[];db.passwordResetRequests.push({email,date:Date.now(),status:'requested'});save();document.getElementById('resetStatus').textContent='Falls ein Konto existiert, wurde die Anfrage gespeichert. In dieser lokalen Demo wird keine E-Mail versendet.'};
};})(window.Deutschraum);

/* Existing profile/session UI. */
(function(runtime){runtime.auth.installProfileUi=function(deps){const {languageOptions,db,save,getUser,setUser,getRoute,setRoute}=deps;
  window.login=function(mode){const languages=languageOptions.map(lang=>'<option>'+lang+'</option>').join('');window.open('<div class="dialog"><div class="dialog-top"><h2>'+(mode==='login'?'Anmelden':'Registrieren')+'</h2><button class="icon">✕</button></div><form class="form" style="margin-top:15px" onsubmit="event.preventDefault();finishAccount(\''+mode+'\')"><label>E-Mail<input id="email" required type="email"></label><label>Passwort<input required type="password" minlength="4"></label>'+(mode==='register'?'<label>Muttersprache<select id="nativeLanguage" required><option value="">Bitte auswählen</option>'+languages+'</select></label>':'')+'<button class="primary">'+(mode==='login'?'Anmelden':'Konto erstellen')+'</button></form></div>');};
  window.finishAccount=function(mode){const address=document.getElementById('email').value.trim().toLowerCase();setUser({email:address});if(!db.users[address])db.users[address]={done:[],right:0,answers:0,words:[],last:{page:'levels',level:'A1'},nativeLanguage:'Russisch',lastActive:Date.now()};const profile=db.users[address];if(mode==='register')profile.nativeLanguage=document.getElementById('nativeLanguage').value;profile.lastActive=Date.now();setRoute(profile.last||{page:'levels',level:'A1'});save();window.close();view();};
  window.profile=function(){const profile=window.prof();if(!profile)return;profile.nativeLanguage=profile.nativeLanguage||'Russisch';window.open('<div class="dialog"><div class="dialog-top"><div><p class="eyebrow">SCHÜLERPROFIL</p><h2>Mein Profil</h2></div><button class="icon">✕</button></div><p>'+esc(getUser().email)+'</p><p class="muted">'+profile.done.length+' Lektionen · '+profile.words.length+' Wörter · '+profile.answers+' Aufgaben</p><form class="form" onsubmit="event.preventDefault();saveProfileLanguage()"><label>Muttersprache<select id="profileNativeLanguage">'+languageOptions.map(lang=>'<option '+(lang===profile.nativeLanguage||lang.startsWith(profile.nativeLanguage+' /')?'selected':'')+'>'+lang+'</option>').join('')+'</select></label><button class="primary">Einstellungen speichern</button><p id="profileMessage" class="task-feedback"></p></form></div>');};
  window.saveProfileLanguage=function(){const profile=window.prof();profile.nativeLanguage=document.getElementById('profileNativeLanguage').value;save();document.getElementById('profileMessage').textContent='✓ Muttersprache gespeichert';};
};})(window.Deutschraum);
