/* Deutschraum: auth responsibilities. Classic scripts preserve HTML handler compatibility. */
function login(m){open('<div class="dialog"><div class="dialog-top"><h2>'+ (m==='login'?'Anmelden':'Registrieren') +'</h2><button class="icon" onclick="close()">✕</button></div><form class="form" style="margin-top:15px" onsubmit="event.preventDefault();finish()"><label>E-Mail<input id="email" required type="email"></label><label>Passwort<input id="accountPassword" required type="password" minlength="4" autocomplete="current-password"></label><p id="accountAuthMessage" class="task-feedback" aria-live="polite"></p><button class="primary">'+(m==='login'?'Anmelden':'Konto erstellen')+'</button></form></div>')}
function finish(){let e=email.value.trim().toLowerCase();user={email:e};if(!db.users[e])db.users[e]={done:[],right:0,answers:0,words:[],last:{page:'levels',level:'A1'}};s=db.users[e].last;save();close();view()}
function logout(){user=null;save();view()}
function profile(){let p=prof();open('<div class="dialog"><div class="dialog-top"><h2>Mein Profil</h2><button class="icon" onclick="close()">✕</button></div><p>'+user.email+'</p><p class="muted">'+p.done.length+' Lektionen · '+p.words.length+' Wörter · '+p.answers+' Aufgaben</p></div>')}

/* Existing final account UI and local reset-request compatibility. */
(function(runtime){runtime.auth.installAccountCompatibility=function({languageOptions,db,save}){
  window.login=function(mode){const languages=languageOptions.map(lang=>'<option>'+lang+'</option>').join('');window.open('<div class="dialog"><div class="dialog-top"><h2>'+(mode==='login'?'Anmelden':'Registrieren')+'</h2><button class="icon">✕</button></div><form class="form" style="margin-top:15px" onsubmit="event.preventDefault();finishAccount(\''+mode+'\')"><label>E-Mail<input id="email" required type="email"></label><label>Passwort<input id="accountPassword" required type="password" minlength="4" autocomplete="current-password"></label>'+(mode==='login'?'<button type="button" class="forgot-link" onclick="openPasswordReset()">Passwort vergessen?</button>':'<label>Muttersprache<select id="nativeLanguage" required><option value="">Bitte auswählen</option>'+languages+'</select></label>')+'<p id="accountAuthMessage" class="task-feedback" aria-live="polite"></p><button class="primary">'+(mode==='login'?'Anmelden':'Konto erstellen')+'</button></form></div>')};
  window.openPasswordReset=function(){window.open('<div class="dialog compact-dialog"><div class="dialog-top"><h2>Passwort zurücksetzen</h2><button class="icon">✕</button></div><form class="form" onsubmit="event.preventDefault();requestPasswordReset()"><p class="muted">Gib deine registrierte E-Mail-Adresse ein.</p><label>E-Mail<input id="resetEmail" type="email" required></label><button class="primary">Reset-Link anfordern</button><p id="resetStatus" class="task-feedback"></p></form></div>')};
  window.requestPasswordReset=function(){const email=document.getElementById('resetEmail').value.trim();db.passwordResetRequests=Array.isArray(db.passwordResetRequests)?db.passwordResetRequests:[];db.passwordResetRequests.push({email,date:Date.now(),status:'requested'});save();document.getElementById('resetStatus').textContent='Falls ein Konto existiert, wurde die Anfrage gespeichert. In dieser lokalen Demo wird keine E-Mail versendet.'};
};})(window.Deutschraum);

/* Existing profile/session UI. */
(function(runtime){runtime.auth.installProfileUi=function(deps){const {languageOptions,db,save,getUser,setUser,getRoute,setRoute}=deps;
  window.login=function(mode){const languages=languageOptions.map(lang=>'<option>'+lang+'</option>').join('');window.open('<div class="dialog"><div class="dialog-top"><h2>'+(mode==='login'?'Anmelden':'Registrieren')+'</h2><button class="icon">✕</button></div><form class="form" style="margin-top:15px" onsubmit="event.preventDefault();finishAccount(\''+mode+'\')"><label>E-Mail<input id="email" required type="email"></label><label>Passwort<input id="accountPassword" required type="password" minlength="4" autocomplete="current-password"></label>'+(mode==='register'?'<label>Muttersprache<select id="nativeLanguage" required><option value="">Bitte auswählen</option>'+languages+'</select></label>':'')+'<p id="accountAuthMessage" class="task-feedback" aria-live="polite"></p><button class="primary">'+(mode==='login'?'Anmelden':'Konto erstellen')+'</button></form></div>');};
  function activateUser(account){const address=String(account?.email||'').trim().toLowerCase();if(!address)return;setUser({id:account.id||null,email:address});if(!db.users[address])db.users[address]={done:[],right:0,answers:0,words:[],last:{page:'levels',level:'A1'},nativeLanguage:'Russisch',lastActive:Date.now()};const profile=db.users[address];profile.lastActive=Date.now();setRoute(profile.last||{page:'levels',level:'A1'});save();}
  window.finishAccount=async function(mode){const address=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('accountPassword')?.value||'',status=document.getElementById('accountAuthMessage');if(runtime.backend?.isConfigured()){if(status)status.textContent=mode==='register'?'Konto wird erstellt …':'Anmeldung läuft …';const result=mode==='register'?await runtime.backend.auth.signUp(address,password):await runtime.backend.auth.signIn(address,password);if(!result.ok){if(status)status.textContent=result.error.message;return}if(mode==='register'&&!result.session){if(status)status.textContent='Bitte bestätige deine E-Mail-Adresse und melde dich danach an.';return}activateUser(result.user);await Promise.all([runtime.backend.isAdmin(),runtime.backend.getEntitlement()]);window.close();view();return}activateUser({email:address});const profile=db.users[address];if(mode==='register')profile.nativeLanguage=document.getElementById('nativeLanguage').value;save();window.close();view();};
  window.logout=async function(){if(runtime.backend?.isConfigured())await runtime.backend.auth.signOut();setUser(null);save();view();};
  window.profile=function(){const profile=window.prof();if(!profile)return;profile.nativeLanguage=profile.nativeLanguage||'Russisch';window.open('<div class="dialog"><div class="dialog-top"><div><p class="eyebrow">SCHÜLERPROFIL</p><h2>Mein Profil</h2></div><button class="icon">✕</button></div><p>'+esc(getUser().email)+'</p><p class="muted">'+profile.done.length+' Lektionen · '+profile.words.length+' Wörter · '+profile.answers+' Aufgaben</p><form class="form" onsubmit="event.preventDefault();saveProfileLanguage()"><label>Muttersprache<select id="profileNativeLanguage">'+languageOptions.map(lang=>'<option '+(lang===profile.nativeLanguage||lang.startsWith(profile.nativeLanguage+' /')?'selected':'')+'>'+lang+'</option>').join('')+'</select></label><button class="primary">Einstellungen speichern</button><p id="profileMessage" class="task-feedback"></p></form></div>');};
  window.saveProfileLanguage=function(){const profile=window.prof();profile.nativeLanguage=document.getElementById('profileNativeLanguage').value;save();document.getElementById('profileMessage').textContent='✓ Muttersprache gespeichert';};
  if(runtime.backend?.isConfigured()){
    runtime.backend.auth.onAuthStateChange(async(_event,session)=>{if(session?.user){activateUser(session.user);await Promise.all([runtime.backend.isAdmin(),runtime.backend.getEntitlement()])}else setUser(null);view()});
    runtime.backend.auth.getSession().then(async result=>{if(result.session?.user){activateUser(result.session.user);await Promise.all([runtime.backend.isAdmin(),runtime.backend.getEntitlement()]);view()}});
  }
};})(window.Deutschraum);
