/* Deutschraum: Beruf & Spezial everyday-situation extension. */
(function(runtime,contentData){
  runtime.lessons.installEverydayCareer=function(deps){
    const {esc,wordify,renderChatSimulator,renderTrueFalseTask}=deps;
    const everydaySituations=contentData.career.everydaySituations;
    /* Alltagssituationen innerhalb von Beruf & Spezial. */
    const retainedEverydayCareer=window.career;
    window.career=function(){const base=retainedEverydayCareer();return base+'<section class="everyday-section"><div class="head"><div><p class="eyebrow">BERUF & ALLTAG</p><h2>Alltagssituationen</h2><p class="muted">Reale Dialoge, passender Wortschatz und interaktive Übungen.</p></div></div><div class="grid cards everyday-grid">'+everydaySituations.map(item=>'<article class="card everyday-card"><span class="everyday-icon">'+item.icon+'</span><h3>'+esc(item.title)+'</h3><p class="muted">'+esc(item.intro)+'</p><button class="primary" onclick="openEverydaySituation(\''+item.id+'\')">Situation üben</button></article>').join('')+'</div></section>'};
    window.openEverydaySituation=function(id){const item=everydaySituations.find(entry=>entry.id===id);if(!item)return;window.open('<div class="dialog everyday-dialog"><div class="dialog-top"><div><p class="eyebrow">ALLTAGSSITUATION</p><h2>'+item.icon+' '+esc(item.title)+'</h2></div><button class="icon">✕</button></div><section class="everyday-intro"><h3>Einführung</h3><p class="clickable-copy">'+wordify(item.intro)+'</p></section><section><h3>Realistischer Dialog</h3>'+renderChatSimulator(item.dialog)+'</section><section><h3>Wortschatz</h3><div class="everyday-vocab">'+item.vocab.map(word=>'<button class="word-tile" onclick="openWordMenu(\''+esc(word).replace(/&#39;/g,"\\'")+'\')">'+esc(word)+' <span>＋</span></button>').join('')+'</div></section><section><h3>Interaktive Übung</h3>'+renderTrueFalseTask(item.statement)+'</section></div>')};

  };
})(window.Deutschraum,window.DeutschraumData);

/* Existing Beruf & Spezial core. */
(function(runtime){runtime.lessons.installCareerCore=function(deps){const {defaultSpecialTopics,esc,mediaHtml,getWordify}=deps;const wordify=value=>getWordify()(value);
  window.career = function () {
    db.specialTopics=Array.isArray(db.specialTopics)?db.specialTopics:[]; const custom=db.specialTopics; const all=[...defaultSpecialTopics,...custom];
    const add=adminOK()?'<button class="primary special-add" onclick="openSpecialAdmin()">＋ Haupt- oder Unterthema</button>':'';
    return '<div class="hero"><p class="eyebrow">BERUFSDEUTSCH</p><h1>Kompetent sprechen. Sicher auftreten.</h1><p>Wortschatz, Praxisdialoge, Lesen und Hören für deinen Beruf.</p></div><div class="head"><div><p class="eyebrow">BERUF & SPEZIAL</p><h2>Fachbereiche</h2></div>'+add+'</div>'+(db.settings.money?gate():'')+'<div class="grid cards">'+all.map((topic,index)=>'<article class="card special-card"><h3>💼 '+esc(topic.name)+'</h3><p class="muted">'+topic.subs.length+' Unterthemen</p><div class="topic-meta">'+[...new Set(topic.subs.map(sub=>sub.category))].map(cat=>'<span>'+esc(cat)+'</span>').join('')+'</div><button class="primary" onclick="openSpecialTopic('+(index-defaultSpecialTopics.length)+',\''+esc(topic.name).replace(/&#39;/g,"\\'")+'\')">Module öffnen</button></article>').join('')+'</div>';
  };
  window.openSpecialAdmin=function(){if(!adminOK())return;const names=[...defaultSpecialTopics,...(db.specialTopics||[])].map(item=>item.name);window.open('<div class="dialog"><div class="dialog-top"><div><p class="eyebrow">ADMIN · BERUF & SPEZIAL</p><h2>Inhalt hinzufügen</h2></div><button class="icon">✕</button></div><form class="form" onsubmit="event.preventDefault();saveSpecialTopic()"><label>Hauptthema<input id="specialMain" list="specialMainList" required placeholder="z. B. Medizin & Pflege"><datalist id="specialMainList">'+names.map(name=>'<option value="'+esc(name)+'">').join('')+'</datalist></label><label>Unterthema<input id="specialSub" required placeholder="z. B. Aufnahmegespräch"></label><label>Bereich<select id="specialCategory"><option>Wortschatz</option><option>Praxisdialoge</option><option>Lesen</option><option>Hören</option></select></label><label>Inhalt<textarea id="specialContent" required></textarea></label><label>audio_url (MP3)<input id="specialAudio" type="url"></label><label>video_url (MP4, YouTube, Vimeo)<input id="specialVideo" type="url"></label><button class="primary">＋ Speichern</button></form></div>');};
  window.saveSpecialTopic=function(){if(!adminOK())return;db.specialTopics=Array.isArray(db.specialTopics)?db.specialTopics:[];const main=document.getElementById('specialMain').value.trim();let topic=db.specialTopics.find(item=>item.name.toLowerCase()===main.toLowerCase());if(!topic){topic={name:main,subs:[]};db.specialTopics.push(topic)}topic.subs.push({title:document.getElementById('specialSub').value.trim(),category:document.getElementById('specialCategory').value,content:document.getElementById('specialContent').value.trim(),audio_url:document.getElementById('specialAudio').value.trim(),video_url:document.getElementById('specialVideo').value.trim()});save();window.close();view();};
  window.openSpecialTopic=function(customIndex,name){if(db.settings.money)return premium();const topic=customIndex>=0?(db.specialTopics||[])[customIndex]:defaultSpecialTopics.find(item=>item.name===name);if(!topic)return;db.analytics.views[name]=(db.analytics.views[name]||0)+1;save();const modules=topic.subs.map((sub,index)=>'<article class="special-module"><div><p class="eyebrow">'+esc(sub.category)+'</p><h3>'+esc(sub.title)+'</h3><p class="clickable-copy">'+wordify(sub.content)+'</p>'+mediaHtml(sub)+(adminOK()&&customIndex>=0?'<button class="danger-button" onclick="deleteSpecialModule('+customIndex+','+index+')">🗑️ Löschen</button>':'')+'</div></article>').join('');window.open('<div class="dialog"><div class="dialog-top"><h2>'+esc(topic.name)+'</h2><button class="icon">✕</button></div><div class="special-modules">'+modules+'</div></div>');};
};})(window.Deutschraum);
